/**
 * Builds the profile world map assets from Natural Earth 110m land (public domain, via world-atlas):
 *
 *   curl -o land-110m.json https://cdn.jsdelivr.net/npm/world-atlas@2/land-110m.json
 *   pnpm tsx scripts/build-land.ts land-110m.json
 *
 * Writes `lib/geo/land.ts` (rings on a 1000×500 equirectangular grid, for the server-rendered hero
 * map and the OG card) and `public/map/land-110m.json` (GeoJSON for the MapLibre night style).
 */
import { readFileSync, writeFileSync } from "node:fs";

type Topology = {
  transform: { scale: [number, number]; translate: [number, number] };
  arcs: Array<Array<[number, number]>>;
  objects: { land: { geometries: Array<{ type: string; arcs: number[][][] | number[][] }> } };
};

const input = process.argv[2];
if (!input) throw new Error("Usage: tsx scripts/build-land.ts land-110m.json");
const topology = JSON.parse(readFileSync(input, "utf8")) as Topology;
const { scale, translate } = topology.transform;

const decoded = topology.arcs.map((arc) => {
  let x = 0;
  let y = 0;
  return arc.map(([dx, dy]) => {
    x += dx;
    y += dy;
    return [x * scale[0] + translate[0], y * scale[1] + translate[1]] as [number, number];
  });
});

function ring(indexes: number[]): Array<[number, number]> {
  const points: Array<[number, number]> = [];
  for (const index of indexes) {
    const arc = index < 0 ? [...(decoded[~index] ?? [])].reverse() : (decoded[index] ?? []);
    points.push(...(points.length ? arc.slice(1) : arc));
  }
  return points;
}

/** Rings that cross the antimeridian jump from +180° to −180°; make them continuous instead. */
function unwrap(points: Array<[number, number]>): Array<[number, number]> {
  const out: Array<[number, number]> = [];
  for (const [lng, lat] of points) {
    let value = lng;
    const previous = out[out.length - 1];
    if (previous) {
      while (value - previous[0] > 180) value -= 360;
      while (value - previous[0] < -180) value += 360;
    }
    out.push([value, lat]);
  }
  // Keep the bulk of the ring on the primary world copy (Eurasia starts at Chukotka, −180°).
  const mean = out.reduce((total, [lng]) => total + lng, 0) / out.length;
  const shift = mean > 180 ? -360 : mean < -180 ? 360 : 0;
  const shifted = out.map(([lng, lat]) => [lng + shift, lat] as [number, number]);
  // Antarctica runs −180°→180° along the coast; close it through the pole, not across the map.
  const first = shifted[0];
  const last = shifted[shifted.length - 1];
  if (first && last && Math.abs(last[0] - first[0]) >= 359) shifted.push([last[0], -90], [first[0], -90]);
  return shifted;
}

const polygons: Array<Array<Array<[number, number]>>> = [];
for (const geometry of topology.objects.land.geometries) {
  const list = (geometry.type === "Polygon" ? [geometry.arcs] : geometry.arcs) as number[][][];
  for (const polygon of list) polygons.push(polygon.map((indexes) => unwrap(ring(indexes))));
}

const round = (value: number, digits: number) => Math.round(value * 10 ** digits) / 10 ** digits;
const geojson = {
  type: "FeatureCollection",
  features: [
    {
      type: "Feature",
      properties: {},
      geometry: {
        type: "MultiPolygon",
        coordinates: polygons.map((polygon) => polygon.map((points) => points.map(([lng, lat]) => [round(lng, 2), round(lat, 2)]))),
      },
    },
  ],
};
writeFileSync("public/map/land-110m.json", JSON.stringify(geojson));

// Equirectangular grid: x = (lng + 180) / 360 × 1000, y = (90 − lat) / 180 × 500.
const grid: number[][] = [];
for (const polygon of polygons) {
  for (const points of polygon) {
    const out: number[] = [];
    let lastX = Number.NaN;
    let lastY = Number.NaN;
    for (const [lng, lat] of points) {
      const x = Math.round(((lng + 180) / 360) * 1000);
      const y = Math.round(((90 - lat) / 180) * 500);
      if (Math.abs(x - lastX) + Math.abs(y - lastY) < 2) continue;
      out.push(x, y);
      lastX = x;
      lastY = y;
    }
    let area = 0;
    for (let index = 0; index < out.length; index += 2) {
      const next = (index + 2) % out.length;
      area += (out[index] ?? 0) * (out[next + 1] ?? 0) - (out[next] ?? 0) * (out[index + 1] ?? 0);
    }
    if (out.length < 6 || Math.abs(area) / 2 < 3) continue;
    grid.push(out);
    // An unwrapped ring that spills past an edge is drawn again from the other side.
    const xs = out.filter((_, index) => index % 2 === 0);
    if (Math.max(...xs) > 1000) grid.push(out.map((value, index) => (index % 2 === 0 ? value - 1000 : value)));
    if (Math.min(...xs) < 0) grid.push(out.map((value, index) => (index % 2 === 0 ? value + 1000 : value)));
  }
}
writeFileSync(
  "lib/geo/land.ts",
  `// Generated by scripts/build-land.ts from Natural Earth 110m land (public domain). Do not edit.\n` +
    `/** Land rings as flat [x0, y0, x1, y1, …] on a 1000×500 equirectangular grid. */\n` +
    `export const LAND_RINGS: readonly (readonly number[])[] = ${JSON.stringify(grid)};\n`,
);
console.log(`polygons ${polygons.length}, grid rings ${grid.length}, points ${grid.reduce((total, item) => total + item.length / 2, 0)}`);
